name: "Build lifecycle"

on:
  - push
  - pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    name: ci

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Validate gradle wrapper
        uses: gradle/wrapper-validation-action@v1

      - name: Setup java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 11
          check-latest: true
          cache: 'gradle'

      - name: Run build lifecycle
        run: ./gradlew
